### ISSUE TITLE
Getting warning from SYBILL "CUT_PRO:   low sqrt(s) "

### ISSUE THREAD

**Issue by mohller** [impy-project/impy#13]
This is more of a suggestion. The warning indicates that sybill received a value for the center of mass energy which is out of the foreseen range. Maybe the EventKinematics class, or the SIBYLLRun class could warn of this and prevent calls. Instead, at the moment, a wrong setting of the kinematics will yield a large amount of warnings when sampling a large number of events. I found the limits parsing the code , and if they could be part of the config parameters, it would be helpful..

**Comment by afedynitch** [comment]
Hi :)

It's a good suggestion to put valid energy ranges for each event generator. It can remain here as suggestion for improvement.

The cut_pro warning says that the energy is too low for sibyll. The minimal energy is ~10 GeV center of mass. It's a choice by the authors to simply warn instead of raise some more serious exceptions. 

If you need lower energy interactions, take DPMJETIII191.

**Comment by HDembinski** [comment]
Not all models warn, some just call stop in Fortran, like EPOS-LHC, which aborts the Python interpreter or kills the Jupyter kernel. We need to catch this in Python to prevent that from happening (and to give users a better error message).
