### ISSUE TITLE
Modernize build system

### ISSUE THREAD

**Issue by HDembinski** [impy-project/impy#5]
One of the things where we spend a lot of time to get it right is building from source with Python. https://github.com/scikit-hep/iminuit/ is the example on how to do this. The actual compilation is done by cmake, which is called from setup.py, so you can do `pip install .` and it will compile the code just fine.

For impy it should also work this way. The build system should detect the OS and set the appropriate options. Once this is in place, it needs to be checked via CI, Github Actions are the best way to do this, they are very easy to set up (certainly easiert than Azure Pipelines).

Then as a next step we should start building binary wheels for each release, using cibuildwheels. An example is here: https://github.com/scikit-hep/iminuit/blob/develop/.github/workflows/wheels.yml

**Comment by HDembinski** [comment]
Using cmake for the build solves several issues.
1) cmake also works on Windows where make is usually not available.
2) cmake can be installed by pip, which means it is can be installed as an install dependency automatically if it is not available.
3) With cmake, you can detect whether the right compiler versions are installed or not and give helpful error messages when they are not available.

**Comment by afedynitch** [comment]
The current setup.py builds wheels.

The build system is tricky and it this is much more work than it may look like and will be a lot of manual labor. I'm not very familiar with cmake and also I don't like it's complexity and obscure search strategies (biased view, sorry). But I know that there are no better alternatives at this moment.

The argument for windows implies an additional steep step, since free Fortran compilers don't exist on this platform:
- Either one can use gfortran 5.3.0 in mingw that can be installed by conda easily. It is not error free but compiles all models, breaking only UrQMD, for example.
- The future is in FLANG. It would allow to remove the vintage GNU tools from the chain. But one needs a very sophisticated test suite for the models. They may build but produce different results since best practices are not followed. Something like equality comparisons on floats is standard, or computed GOTO from truncated integer division to give a few examples. This is also a very labor intense task and may entirely fail.

**Comment by afedynitch** [comment]
World seemed to have moved on to [MESON](https://mesonbuild.com/index.html). I prefer it so much more than CMAKE

**Comment by HDembinski** [comment]
There are several advantage to using cmake:
- Many large projects successfully use cmake to build their wheels, and also smaller projects like iminuit and pyhepmc
- You can pip install cmake, which means you can define cmake as a dependency for the build in pyproject.toml that is automatically installed if it is not available
- I have experience with cmake, but not meson, so I cannot help with the latter

**Comment by HDembinski** [comment]
Required changes to build system
- [ ] Move away from setup.py to setup.cfg and project.toml, following recent updates to Python's build sytem; once can see how it is done in iminuit and pyhepmc, for example; essentially setup.py becomes a small stub and may disappear completely in the future
- [ ] `pip install -e .` does not compile the FORTRAN interface, you have to call make separately, but pip install should also run the compiling, just like it is done for iminuit or pyhepmc and many other packages
- [ ] make does not support building on multiple platforms very well, that's why we need cmake
- [ ] the folder `impy` needs to be moved to `src/impy`, to avoid importing it when testing `impy` from the project directory. That is another best practice observed by professional packages. You can still test changes to the source code immediately by installing the package in develop mode with `pip install -e .`
- [ ] AFAIU, numpy < 1.20 is required at the moment, but this versioned requirement is not declared in setup.py

**Comment by afedynitch** [comment]
Looking more into what's going on with the updated numpy and f2py issues (see #11), it seems that the problem might come from numpy moving away from distutils and cmake. As far as I understand, numpy is moving to MESON.

See also [this for some updates on f2py](https://m.youtube.com/watch?v=9nMSKcRimuw)

So +1 for MESON? :)

**Comment by HDembinski** [comment]
If you implement it and maintain it, but please consider the practical implications. Meson is probably a very nice build system, but I have zero experience with it, so I cannot help here. That is also true for large parts of the internet. If you have a problem with CMake, you can probably google a solution, thanks to its wide-spread use. Try that with Meson. I can help setting up a cmake build, because I have done that before in several projects.

I don't know how familiar you are with modern package building. Look at iminuit's setup.py. There is basically nothing left there:
https://github.com/scikit-hep/iminuit/blob/develop/setup.py
The future plan by the Python packaging authority is to get rid of it altogether.

How the package is build is described here:
https://github.com/scikit-hep/iminuit/blob/develop/pyproject.toml
The build-system uses cmake, which is a Python package and thus be installed by pip to prepare the build environment. The user does not have to have cmake installed, and since the build environment is isolated, they will barely notice that cmake is installed at all.

We have this ready-made CMakeExtension for setuptools, which runs cmake to build the project:
https://github.com/scikit-hep/iminuit/blob/develop/cmake_ext.py
This is general code and can be used to build other projects.

The only thing we really need to implement is the CMakeLists.txt. If you insist on using Meson, you need to write a MesonExtension for setuptools.

Numpy builds with setuptools, it does not use a build system.
https://github.com/numpy/numpy/

Scipy is apparently using meson, but have fun understanding the very complex code that Scipy is running. I don't understand this and I wouldn't be able to copy from them.
https://github.com/scipy/scipy

**Comment by eli-schwartz** [comment]
> There are several advantage to using cmake:
> 
>   * Many large projects successfully use cmake to build their wheels, and also smaller projects like iminuit and pyhepmc

I'm not sure this is either an advantage or a disadvantage. This project successfully uses Make to build the wheel, does that count as an advantage of Make? :p

>   * You can pip install cmake, which means you can define cmake as a dependency for the build in pyproject.toml that is automatically installed if it is not available

You can also pip install Meson, and define it as a dependency for the build in pyproject.toml -- in fact, somewhat more naturally than cmake, since cmake is a C++ executable sideloaded into wheels, while Meson is written in python and sort of has to be pip-installable.





> The only thing we really need to implement is the CMakeLists.txt. If you insist on using Meson, you need to write a MesonExtension for setuptools.

You do not. :) Meson has two PEP 517 build backends that don't use setuptools at all, SciPy is using https://pypi.org/project/meson-python/

You can simply drop setuptools altogether.

> Numpy builds with setuptools, it does not use a build system.
> https://github.com/numpy/numpy/

The SciPy/NumPy community has first (successfully) experimented with converting SciPy from setuptools "without a build system" to Meson, and NumPy formally documents:

> NumPy itself will very likely migrate to Meson as well, once the SciPy migration is done.

I would say it's just a matter of time and putting in the work. :)


> Scipy is apparently using meson, but have fun understanding the very complex code that Scipy is running. I don't understand this and I wouldn't be able to copy from them.
> https://github.com/scipy/scipy

SciPy has a pretty complex build regardless, as far as numpy.distutils former users go. They've mentioned that that makes it a good stress test for migration. There are simpler examples out there. And NumPy provides an example walkthrough for f2py usage specifically, here: https://numpy.org/doc/stable/f2py/buildtools/meson.html


...

If you are interested in using cmake, that's great. Moving on from setuptools which is hard to extend, or GNU make which has its own significant challenges, is 100% a good thing regardless of which choice you move to.

And if you are interested in using Meson, that's also great. I'd be happy to advise, in that case. I'm a Meson developer, and I've been helping the SciPy team with various Meson integration bits, adding a few features they needed, etc.

**Comment by HDembinski** [comment]
For the record, I am working on a prototype for cmake based build right now.

**Comment by HDembinski** [comment]
Draft is evolving here https://github.com/impy-project/impy/pull/39

**Comment by HDembinski** [comment]
> @HDembinski I disagree that the makefiles never successfully built wheels.

That is a strawman argument. I didn't say that they never successfully built wheels. I am saying that they don't work on my system, and that they probably do not work on many other systems. To which your answer was so far "but it works for me", which is not very helpful. By saying that you are pushing the problem onto me, while it is your responsibility as maintainer to make sure your software works.

Supporting multiple platforms is hard, I know this from experience. Just because somethings works on your particular computer does not mean it works everywhere. So far you did not have CI to build/test on multiple systems. You just didn't see your old system failing.

> Probably on a clean install without all the venvs, and compiler aliases, it will simply build.

We need to support venvs and we have to deal with compiler aliases, because that's the world we live in.

> Since 10 years it builds on my mac, and it does so on other macs.

I have a Mac, too, you know.

> Makefiles simply didn’t adapt well to the circumstances because world moved on quite rapidly.

That's exactly my point, so why are we arguing?

> I personally dislike cmake very much, because if it's awkward design. But people got used to it.

I agree with you, but I am pragmatic, too.

> Meson is clearly my preference due to its much cleaner design philosophy and the pythonic hacks one could do to solve the problems.

> Since there is plenty of momentum in the community for Meson, I believe it is the right choice to go for the project. And seeing so many project moving over to Meson speaks for itself.

There is no problem that you can solve with Meson but not with CMake. As you said, the salient point to avoid letting f2py run the compiler, because it uses distutils for that and distutils is fairly broken (which is why everyone use cmake/meson/...).
 
> @HDembinski I don’t see that clear reason to really reject meson so hard. Is there any example where you made bad experience with it?

Strawman argument again. I do not reject meson, but since I am the one working on improving the build system at the moment, I will not try to do that and learn Meson at the same time. I don't have time for that. I also simply do not trust Meson right now, because I have no experience with it. When I run into problems with CMake, I know how to solve them at least. These are very reasonable arguments which I already gave, so we are running in circles here.

Besides, this whole discussion about which build system to use is just a distraction from doing actual work. If you compare https://numpy.org/devdocs/f2py/buildtools/cmake.html and https://numpy.org/devdocs/f2py/buildtools/meson.html, they are not really that different. Meson is just running different commands.

What I personally want is to build impy on my computer without a docker container, so that I can actually use it for work and experiment with better API design. And I want this sooner rather than later. So I am trying to work out a solution with CMake. Feel free to replace all this with Meson, but let's finish this part first.
