### ISSUE TITLE
4-vectors from event_kinematics off shell

### ISSUE THREAD

**Issue by afedynitch** [impy-project/impy#58]
```
event_kinematics = EventKinematics(
   ecm= 5 * TeV,
   p1pdg=lp.proton.pdgid,
   p2pdg=lp.proton.pdgid
)

In [9]: event_kinematics.ecm - ( p1[3] + p2[3])
Out[9]: 0.00035214024956076173
```
Problem. Maybe `pcm` calculation wrong.

The example uses a modification of setting `ecm` for the 4-vectors like `np.sqrt(self.pcm**2 + self.m**2)`. Maybe it's just round-off errors...

**Comment by afedynitch** [comment]
@kotania Weren't you the last one to "repair" the `pcm` calculation? :)

**Comment by kotania** [comment]
Yes, as per this commit: https://github.com/kotania/impy/commit/1cf20990d4ecf736b4c8bd753375f079a510133b 

The units were wrong before: s^2 has the units of energy^2, and pmass1 (pmass2) have units of energy, so adding them together didn't make sense.

See formula (2.10) here: https://edu.itp.phys.ethz.ch/hs10/ppp1/PPP1_2.pdf

Actually just noticing that as per this formula, [this line](https://github.com/impy-project/impy/blob/master/src/impy/kinematics.py#L264 ) should have `2 * (s * (pmass1**2 + pmass2**2)` ... instead of `2 * (s * (pmass1 + pmass2)**2`. Correct me if I'm wrong, and let me know if this helps!

**Comment by kotania** [comment]
Yes, as per this commit: https://github.com/kotania/impy/commit/1cf20990d4ecf736b4c8bd753375f079a510133b 

The units were wrong before: s^2 has the units of energy^2, and pmass1 (pmass2) have units of energy, so adding them together didn't make sense.

See formula (2.10) here: https://edu.itp.phys.ethz.ch/hs10/ppp1/PPP1_2.pdf

Actually just noticing that as per this formula, [this line](https://github.com/impy-project/impy/blob/master/src/impy/kinematics.py#L264 ) should have `2 * (s * (pmass1**2 + pmass2**2)` ... instead of `2 * (s * (pmass1 + pmass2)**2`. Correct me if I'm wrong, and let me know if this helps!

**Comment by jncots** [comment]
> have `2 * (s * (pmass1**2 + pmass2**2)` ... instead of `2 * (s * (pmass1 + pmass2)**2`. 

Yes, the problem was because of this.

**Comment by jncots** [comment]
Commit 536ee90ba0c862d9904e93bcc5c2f6352e16aabc fixes the problem
