### ISSUE TITLE
EPOS fails with nuclear projectiles / targets

### ISSUE THREAD

**Issue by HDembinski** [impy-project/impy#79]
EPOS should work with initial nuclear particles, but when I try this it fails. Has anyone tried this out before?

**Comment by afedynitch** [comment]
I did. Are you passing the heaviest mass you want to use to the constructor?

**Comment by HDembinski** [comment]
I am just using the EposLHC model in impy.

**Comment by HDembinski** [comment]
initializeepos rejects inputs where I pass a pdgid that describes a nuclues.

**Comment by HDembinski** [comment]
Before that, the only other call I can see to EPOS is aaset(0)

**Comment by afedynitch** [comment]
@HDembinski @jncots: so the reason is that `EventKinematics` is returning nuclear PDG particle codes now and EPOS complains about this. Except maybe pythia8 none of the models uses these codes. So formally, they are fine, but it's not how their interfaces work. They require either a proton or neutron as a PDG code.

We would need to either, make flags in the configs, so EventKinematics knows what to pass, or, the models need to grab the right ones. It's clearly a bug and needs to be fixed. IMO, it would make sense to fix it together with #80 .

**Comment by HDembinski** [comment]
> So formally, they are fine, but it's not how their interfaces work.

Then I think that's an implementation detail that should be handled by each model. Btw, in case of EPOS, Tanguy told me that he does not recognize the function `initializeepos`, so where does this come from? If it is a function that we wrote anyway, we can just change it to accept nuclear PDG codes. I think it is a bit weird to pass pdg and A and Z, when A and Z can be computed from pdg.

**Comment by afedynitch** [comment]
PR #81 fixes this issue by accepting only PDG ids for initializer functions.

**Comment by afedynitch** [comment]
Closed by #81
