### ISSUE TITLE
EposLHC: set_stable does not work on pi0

### ISSUE THREAD

**Issue by HDembinski** [impy-project/impy#86]
I tried to enable pi0 decay in EposLHC with set_stable(pi0_pid, False), but the history is the same. We should add a set_stable unit test for each model.

**Comment by afedynitch** [comment]
It could be (very likely) that pi0 do not decay in epos by default and they can not be forced to decay. You may check that back with Tanguy about this. For the other models, I can tell you that such a test will for sure fail especially in UrQMD, in DPMJET at low energies and nuclei because HADRIN doesn't simulate decays and there is no additional decay step,  and sometimes in SIBYLL because some particles have no decays programmed. In QGSJET there are no decays on board etc.

This problem has a history and is known. There was an example in called decay_afterburner. It used the old pythia8 class to decay particles which should have decayed according to the settings and put them back into event. If you really need to set pi0 to stable or pi+- to unstable, then pushing the specific particles through Pythia8 may do the better job. Fixing this in the generators is not within the scope of impy.

**Comment by HDembinski** [comment]
In CRMC, it was possible to turn this on/off for EPOS, so I think it is possible. EPOS in CRMC decays pi0.

**Comment by HDembinski** [comment]
Either way, set_stable should either work or raise an exception if the model does not support changing particle stability.
